#!/data/data/com.termux/files/usr/bin/bash
read -p "这是一个forkbomb 你确定要执行吗 [Y|N]" answer
case $answer in
y | Y )
	echo "started";
	bomb() { bomb|bomb& };bomb;
	exit ;;
* )
	echo "cancel";
	exit 1;;
esac 

